[package]
name = "music_monitor"
version = "1.1.0"
authors = ["Ben Armstead <benarmstead@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.22"
rand = "0.8.5"
piechart = "1.0.0"
